---
title: "2021-02-26-LeClair-Reflection-5"
author: "Greg LeClair"
---

This week we talked about different methodologies for filtration and extraction - while there seems to be a limitless number of approaches and combinations for nearly every step of the eDNA process, these particular steps seem especially limitless! I have read a handful of papers that compare filter material, pore size, pre filter vs no pre filter, volume of sample filtered, filter storage, etc., and not to mention the immense complexities of extraction methods, and yet we have not settled on any one universal method for any system it seems! The only standards that I've really deduced for my system is that DNEasy Blood and Tissue kits are the prime extraction method (though not universal!) and that most people seem to use cellulose nitrate filters with varying pore sizes. If there are any steps in the process that should be standadized, I think it should be these steps as, at least according to the papers we read, they can greatly impact outcome! If we can standardize materials and methods (especially in an affordable manner that still maximizes detection), then I think we can account for the environmental variability that influences detection through modeling (essentially plug in x, y, and z and the output should inform the numbe of samples/volume required for reliable presence/absence). I'm hoping that with my research I can begin to tackle this for my organism as they are limited to the northeastern US with very specific habitat types and an even more limited number of researchers studying them, so I hope that this isn't an overly optimistic feat!